/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/bitget_futures/json/contracts.hpp"

using namespace roq;
using namespace roq::bitget_futures;

using namespace std::literals;

// note! reduced
TEST_CASE("json_contracts_item", "[json_contracts]") {
  auto message = R"({)"
                 R"("code":"00000",)"
                 R"("msg":"success",)"
                 R"("requestTime":1756171964139,)"
                 R"("data":[{)"
                 R"("symbol":"BTCUSD",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USD",)"
                 R"("buyLimitPriceRatio":"0.05",)"
                 R"("sellLimitPriceRatio":"0.05",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("supportMarginCoins":["BTC","STETH","XRP","ETH","USDE","USDC","BGB"],)"
                 R"("minTradeNum":"0.0001",)"
                 R"("priceEndStep":"1",)"
                 R"("volumePlace":"4",)"
                 R"("pricePlace":"1",)"
                 R"("sizeMultiplier":"0.0001",)"
                 R"("symbolType":"perpetual",)"
                 R"("minTradeUSDT":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("symbolStatus":"normal",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"",)"
                 R"("deliveryStartTime":"",)"
                 R"("deliveryPeriod":"",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"8",)"
                 R"("minLever":"1",)"
                 R"("maxLever":"125",)"
                 R"("posLimit":"0.1",)"
                 R"("maintainTime":"",)"
                 R"("openTime":"",)"
                 R"("maxMarketOrderQty":"20",)"
                 R"("maxOrderQty":"100")"
                 R"(},{)"
                 R"("symbol":"ETHUSD",)"
                 R"("baseCoin":"ETH",)"
                 R"("quoteCoin":"USD",)"
                 R"("buyLimitPriceRatio":"0.05",)"
                 R"("sellLimitPriceRatio":"0.05",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("supportMarginCoins":["BTC","STETH","XRP","ETH","USDE","USDC","BGB"],)"
                 R"("minTradeNum":"0.01",)"
                 R"("priceEndStep":"1",)"
                 R"("volumePlace":"2",)"
                 R"("pricePlace":"2",)"
                 R"("sizeMultiplier":"0.01",)"
                 R"("symbolType":"perpetual",)"
                 R"("minTradeUSDT":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("symbolStatus":"normal",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"",)"
                 R"("deliveryStartTime":"",)"
                 R"("deliveryPeriod":"",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"8",)"
                 R"("minLever":"1",)"
                 R"("maxLever":"100",)"
                 R"("posLimit":"0.1",)"
                 R"("maintainTime":"",)"
                 R"("openTime":"",)"
                 R"("maxMarketOrderQty":"400",)"
                 R"("maxOrderQty":"2000")"
                 R"(},)"
                 // ...
                 R"({)"
                 R"("symbol":"BTCUSDZ25",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USD",)"
                 R"("buyLimitPriceRatio":"0.05",)"
                 R"("sellLimitPriceRatio":"0.05",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("supportMarginCoins":["BTC"],)"
                 R"("minTradeNum":"0.001",)"
                 R"("priceEndStep":"1",)"
                 R"("volumePlace":"3",)"
                 R"("pricePlace":"1",)"
                 R"("sizeMultiplier":"0.001",)"
                 R"("symbolType":"delivery",)"
                 R"("minTradeUSDT":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("symbolStatus":"normal",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"1766736000000",)"
                 R"("deliveryStartTime":"1751011204758",)"
                 R"("deliveryPeriod":"next_quarter",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"",)"
                 R"("minLever":"1",)"
                 R"("maxLever":"50",)"
                 R"("posLimit":"",)"
                 R"("maintainTime":"",)"
                 R"("openTime":"1751011158257",)"
                 R"("maxMarketOrderQty":"",)"
                 R"("maxOrderQty":"")"
                 R"(})"
                 R"(])"
                 R"(})";
  core::json::BufferStack buffer{8192, 1};
  [[maybe_unused]] json::Contracts obj{message, buffer};
}
