/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/bitget_futures/json/currencies.hpp"

using namespace roq;
using namespace roq::bitget_futures;

using namespace std::literals;

// note! reduced
TEST_CASE("json_currencies", "[json_currencies]") {
  auto message = R"({)"
                 R"("code":"00000",)"
                 R"("msg":"success",)"
                 R"("requestTime":1756171963029,)"
                 R"("data":[{)"
                 R"("coinId":"1460",)"
                 R"("coin":"U2U",)"
                 R"("transfer":"false",)"
                 R"("chains":[{)"
                 R"("chain":"UnicornUltraSolaris",)"
                 R"("needTag":"false",)"
                 R"("withdrawable":"true",)"
                 R"("rechargeable":"true",)"
                 R"("withdrawFee":"0.01",)"
                 R"("extraWithdrawFee":"0",)"
                 R"("depositConfirm":"20",)"
                 R"("withdrawConfirm":"40",)"
                 R"("minDepositAmount":"1.49365197",)"
                 R"("minWithdrawAmount":"1493.65197908",)"
                 R"("browserUrl":"https://u2uscan.xyz/tx/",)"
                 R"("contractAddress":null,)"
                 R"("withdrawStep":"0",)"
                 R"("withdrawMinScale":"8",)"
                 R"("congestion":"normal")"
                 R"(})"
                 R"(],)"
                 R"("areaCoin":"no")"
                 R"(},)"
                 R"({)"
                 R"("coinId":"1459",)"
                 R"("coin":"WUF",)"
                 R"("transfer":"false",)"
                 R"("chains":[{)"
                 R"("chain":"SOL",)"
                 R"("needTag":"false",)"
                 R"("withdrawable":"true",)"
                 R"("rechargeable":"false",)"
                 R"("withdrawFee":"8542131.47909878",)"
                 R"("extraWithdrawFee":"0",)"
                 R"("depositConfirm":"10",)"
                 R"("withdrawConfirm":"10",)"
                 R"("minDepositAmount":"85421.31479098",)"
                 R"("minWithdrawAmount":"85421314.79098775",)"
                 R"("browserUrl":"https://solscan.io/tx/",)"
                 R"("contractAddress":"73xsLcBnLnc9bh81cqVKqj8uEyiarXng5ZwJuTbnVebG",)"
                 R"("withdrawStep":"0",)"
                 R"("withdrawMinScale":"8",)"
                 R"("congestion":"normal")"
                 R"(})"
                 R"(],)"
                 R"("areaCoin":"no")"
                 R"(},)"
                 // ...
                 R"({)"
                 R"("coinId":"1449",)"
                 R"("coin":"LSD",)"
                 R"("transfer":"false",)"
                 R"("chains":[{)"
                 R"("chain":"Aptos",)"
                 R"("needTag":"false",)"
                 R"("withdrawable":"true",)"
                 R"("rechargeable":"false",)"
                 R"("withdrawFee":"2.19748023",)"
                 R"("extraWithdrawFee":"0",)"
                 R"("depositConfirm":"10",)"
                 R"("withdrawConfirm":"10",)"
                 R"("minDepositAmount":"0.03662467",)"
                 R"("minWithdrawAmount":"36.62467037",)"
                 R"("browserUrl":"https://aptoscan.com/transaction/",)"
                 R"("contractAddress":"0x02370cc1d995f3aadd337c1c6c63834ad8d2bd0cdc70bc8dff81de463e18b159",)"
                 R"("withdrawStep":"0",)"
                 R"("withdrawMinScale":"8",)"
                 R"("congestion":"normal")"
                 R"(})"
                 R"(],)"
                 R"("areaCoin":"no")"
                 R"(})"
                 R"(])"
                 R"(})";
  core::json::BufferStack buffer{8192, 1};
  [[maybe_unused]] json::Currencies obj{message, buffer};
}
